name: carrie
services:
  development:
    build:
      args:
        UID: ${UID}
        GID: ${GID}
        USER: ${USER}
        REPO: ${REPO}
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c '
        export PATH="/usr/lib/ccache:$PATH" &&
        source /opt/ros/jazzy/setup.bash &&
        exec bash
      '
    container_name: ${USER}-${REPO}-dev
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
      - TERM=xterm-256color
    extra_hosts:
      - ${REPO}-dev:127.0.0.1
    hostname: ${REPO}-dev
    image: ${REPO}-dev:latest
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
      - ~/.ssh:${HOME}/.ssh:ro
      - ~/.gitconfig:${HOME}/.gitconfig:ro
      - ${PWD}:${HOME}/ws/src
      - ~/.${REPO}/ccache:${HOME}/.ccache
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    working_dir: ${HOME}/ws
